### ISSUE TITLE
Second tab slider and chart!

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_dashboards#19]
Thanks @rita-ni for the work on tab 1. Good job!

I have added interactive slider to second tab and it works as expected. But for return percentages as @YueJiangMDSV suggested we will need to wrangle data(shouldn't take much time)..
After that adding it to tab wont be a bigger deal i guess!

**Comment by YueJiangMDSV** [comment]
Hi team, 

I was able to produce Tab 2 based on @rita-ni 's code. I wrangled the data, and changed the return percentages to monthly investment return percentage. We can discuss more tomorrow.
Big big thanks to @rita-ni ! Well done! Amazing!

Alex

**Comment by arunmarria** [comment]
Sounds good. Lets meet after lab and discuss this. Seems like we are on right track to finish this soon!

**Comment by arunmarria** [comment]
Closing this as slider on second chart is sorted out.
