### ISSUE TITLE
Deploying app on Heroku

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_dashboards#20]
Good news team, our app gets deployed after commenting
`#import dash_bootstrap_components as dbc`

Check demo version here

https://arun-lecture3app.herokuapp.com/

**Comment by arunmarria** [comment]
@rita-ni @YueJiangMDSV Also one of us will need to create an account on Heroku to host final version of the app. Lets try doing that at the soonest so we are aware of any issues in advance!

**Comment by YueJiangMDSV** [comment]
Hey team, 

This is the updated version  https://dsci532-test-app.herokuapp.com/
