### ISSUE TITLE
Suggestion of improvements

### ISSUE THREAD

**Issue by KarlosMuradyan** [UBC-MDS/DSCI-532_group-211_dashboards#37]
The app is really good, but I would like to give some suggestions of improvements and bugs that we found:

- Stock price chart in the Stock Trends is a little bit different than Investment Value Chart in "Investment Value" tab. All lines except the Google were consistent, but the Google lineplot was lower than that in the Stock price chart
- Time Period was a little bit invisible at first in the "Investment Value" tab
- In the "Stock Trends" tab you had typo
- Y-axis labels in the second section of  "Stock Trends" tab were confusing. What did the floating numbers represent?
- It will be great to choose the time of the investment in "Investment Value" tab.

**Comment by arunmarria** [comment]
Thanks for the feedback @KarlosMuradyan ; changes have been incorporated in #40
