### ISSUE TITLE
Peer Review Feedback

### ISSUE THREAD

**Issue by andrealee011** [UBC-MDS/DSCI-532_group-211_dashboards#38]
What to fix:
- when you clear dropdown selection in stock trends everything goes blank (maybe add some text that will show up that says "nothing selected" or "please make a selection")
- try to make it so you only have one vertical slider in stock trends
- fix wording in investment value
- fix typo in stock trends
- move time period slider to the top in investment value
- make about our data more visually appealing

What we liked:
- the insights you provided on your graphs
- the time period filtering in stock trends
- the description of your dataset in about our data

**Comment by arunmarria** [comment]
Thanks for feedback @andrealee011 ; changes have been incorporated in #40
