### ISSUE TITLE
Milestone 3 Group Feedback Session  

### ISSUE THREAD

**Issue by MrThomasPin** [UBC-MDS/DSCI-532_group-211_dashboards#39]
•	Good table about our data because financial literary make the table small and leaner 

•	The drop-down menu seemed to be broken on the stock tab. Furthermore, a selection bar would be better for 5 companies instead of a search.  

•	The monthly change % was missing the y-title 

•	The hover on the tooltip color is cool. 

•	The time Slide bar for the investment value was not working.

•	Google dominated the y-axis because it had such a large stock price value made it hard to see the other stock prices. Maybe a way removes Google. 

•	There was a typo on the stock prices tab. 

•	Just focus on bug fix

**Comment by arunmarria** [comment]
Thanks for the feedback Thomas; changes have been incorporated in #40
