### ISSUE TITLE
Summary of peer feedback session

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_dashboards#40]
**Things need to work on(in order of priority)**

-  A couple typos in title/text (tab 2 type fixed)
- Time slider should be at the top on investment value chart
- Explaination for monthly chart
- Explaination for different trends in investment value(text below plot)
- Two scroll bars (fixed-rn)
- Comparison vertical line-- Altair
- Fixed slider (don't know need to check)
- More colors(visually appealing)

**Things we nailed**

- Systematic layout
- Data set intro
- Different tabs layout
- Slider on second tab 
- Second research question - how much would investment be after some time?
- Short insights at top of each chart

Link to issues corresponding to feedback #39 #38  #37

**Comment by arunmarria** [comment]
**Things need to work on(in order of priority)**

- A couple typos in title/text (tab 2 type fixed)
- Time slider should be at the top on investment value chart
- Explanation for monthly chart
- Explanation for different trends in investment value(text below plot)
-  ~~Two scroll bars~~  **Fixed**. 
- Comparison vertical line-- Altair
- Fixed slider (don't know need to check)
- More colors(visually appealing)

**Comment by arunmarria** [comment]
Here is current status on maintenance of the python app
cc @YueJiangMDSV @rita-ni  

**Things need to work on(in order of priority)**

- A couple typos in title/text (tab 2 type fixed) --> **might make sense for @YueJiangMDSV  to do that ?**
-  ~~Time slider should be at the top on investment value chart~~ -->**fixed**
- Explanation for monthly chart --> **might make sense for @YueJiangMDSV  to do that ?**
- Explanation for different trends in investment value(text below plot)
- Two scroll bars **Fixed.** -by Rita
- ~~Code cleaning~~/refactoring --> **need to see if more can be done**
- Comparison vertical line-- Altair
- Fixed slider (don't know need to check)
- More colors(visually appealing)

**Comment by YueJiangMDSV** [comment]
Sure, I can do the above two things: fixing typo and explanation for monthly chart. I can also try to add explanation for different trends in investment value

**Comment by YueJiangMDSV** [comment]
Things need to work on(in order of priority)

~~A couple typos in title/text (tab 2 type fixed)~~ --> I did not find the other typo we were talking about the other day. Is there any other typos?
~~Time slider should be at the top on investment value chart~~ -->fixed
~~Explanation for monthly chart~~ --> Added title and labels
~~Explanation for different trends in investment value(text below plot)~~ -->fixed Added explanation
~~Two scroll bars Fixed.~~ -by Rita
~~Code cleaning~~/refactoring --> ? @rita-ni anything?
Comparison vertical line-- Altair
Fixed slider (don't know need to check)
More colors(visually appealing)

**Comment by rita-ni** [comment]
Things need to work on(in order of priority)

~~A couple of typos in title/text~~ --> both typo in tab 3 fixed
~~Time slider should be at the top on investment value chart~~ --> fixed
~~Explanation for monthly chart~~ --> Added title and labels
~~Explanation for different trends in investment value(text below plot)~~ -->fixed Added explanation
~~Two scroll bars Fixed.~~ - fixed
~~Code cleaning~~/refactoring --> to do
Comparison vertical line-- Altair
Fixed slider (don't know need to check)
More colors(visually appealing)

**Comment by rita-ni** [comment]
By now issues above are addressed, closing this issue
