### ISSUE TITLE
Explain some updates

### ISSUE THREAD

**Issue by YueJiangMDSV** [UBC-MDS/DSCI-532_group-211_dashboards#47]
Hi team,

I have made a new pull request and here is the things I did:

1. Since we changed the app layout (from plotly to altair), I changed the sketch as well.
2. Based on Milestone3 requirement, I updated the proposal and the readme files to reflect the updates in our app.
3. I also updated the reflection based on Milestone 3 requirements.

Please take a look and see if there is anything we need to improve. Feel free to update the files if you see necessary.
Thanks!

**Comment by rita-ni** [comment]
@YueJiangMDSV 

Wow I really like the new sketch, Thank you Alex for the awesome work!!
