### ISSUE TITLE
Image blurring in sketch

### ISSUE THREAD

**Issue by YueJiangMDSV** [UBC-MDS/DSCI-532_group-211_dashboards#6]
For the graph blurring issue, I can save the graphs as svg files and then send them to you guys. Or you can run it in Jupyter and save the graphs by yourself. Once they are saved as svg files, they won't blur any more

**Comment by arunmarria** [comment]
Sure will do that shortly and update the sketch. Thanks for checking!

**Comment by arunmarria** [comment]
The images get a little blurred coz of screenshot which I took after preparing word doc for sketch. I am not sure if we can re-size image in readme. If any of you know please feel free to do that(by forking in local repo first and then creating pull req. )

**Comment by arunmarria** [comment]
Made required changes
